name: Generate Table of Contents

on:
  push:
    branches:
      - master
    paths:
      - 'README.md'

jobs:
  generateTOC:
    runs-on: ubuntu-latest

    steps:
      - name: TOC Generator
        uses: neuenmuller/toc-generator@3d54e40125014baed3ba75617c44af2a42b9f67d
        with:
          TARGET_PATHS: README.md
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TOC_TITLE: ''
          ENTIRE: true
